export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userContants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};
export const getAllProduct = {
    GETALL_PRODUCT_REQUEST: "GETALL_PRODUCT_REQUEST",
    GETALL_PRODUCT_SUCCESS: "GETALL_PRODUCT_SUCCESS",
    GETALL_PRODUCT_FAILURE: "GETALL_PRODUCT_FAILURE",
};
export const addAddress = {
    ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
    ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",
};
export const addPatient = {
    ADD_PATIENT_REQUEST: "ADD_PATIENT_REQUEST",
    ADD_PATIENT_SUCCESS: "ADD_PATIENT_SUCCESS",
    ADD_PATIENT_FAILURE: "ADD_PATIENT_FAILURE",
};
export const getPatient = {
    GET_PATIENT_REQUEST: "GET_PATIENT_REQUEST",
    GET_PATIENT_SUCCESS: "GET_PATIENT_SUCCESS",
    GET_PATIENT_FAILURE: "GET_PATIENT_FAILURE",
};
export const AddToCart = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
};
export const getItemToCart = {
    GETITEM_TO_CART_REQUEST: "GETITEM_TO_CART_REQUEST",
    GETITEM_TO_CART_SUCCESS: "GETITEM_TO_CART_SUCCESS",
    GETITEM_TO_CART_FAILURE: "GETITEM_TO_CART_FAILURE",
};
export const RemoveItemToCart = {
    REMOVEITEM_TO_CART_REQUEST: "REMOVEITEM_TO_CART_REQUEST",
    REMOVEITEM_TO_CART_SUCCESS: "REMOVEITEM_TO_CART_SUCCESS",
    REMOVEITEM_TO_CART_FAILURE: "REMOVEITEM_TO_CART_FAILURE",
};

export const addOrder = {
    ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST",
    ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
    ADD_ORDER_FAILURE: "ADD_ORDER_FAILURE",
}
export const getOrder = {
    GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
}
export const getAddress = {
    GET_ADDRESS_REQUEST: "GET_ADDRESS_REQUEST",
    GET_ADDRESS_SUCCESS: "GET_ADDRESS_SUCCESS",
    GET_ADDRESS_FAILURE: "GET_ADDRESS_FAILURE",
}